##### APP NAME ########
spring.application.name=demoApp
#####LOCAL DATABASE CONFIGURATION########
spring.datasource.url=jdbc:mariadb://localhost:3306/master_liquibase_db2?allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=Secret!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


###### LIQUIBASE CONFIGURATION#######
spring.liquibase.enabled=true 
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
logging.level.liquibase=DEBUG

spring.mvc.hiddenmethod.filter.enabled=true


#============= 404 exceptions enabler
spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false

